version: '2'

services: 
    mariadb:
        image: mariadb
        volumes:
            - ~/data/db:/var/lib/mysql
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        expose: 
            - "3306"
        restart: always

        networks:
            - inception
        env_file: .env

    wordpress:
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - ~/data/wp:/var/www/wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        expose:
            - "9000"
        networks:
            - inception
        env_file: .env

    nginx:
        image: nginx
        depends_on:
            - wordpress
        volumes:
            - ~/data/wp:/var/www/wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "443:443"
        networks:
            - inception
        env_file: .env

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: ~/data/db
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: ~/data/wp
            o: bind

networks:
    inception:
        driver: bridge